# Generated by Django 5.1.15 on 2026-09-22 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "short_code",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("original_url", models.URLField(max_length=2048)),
                ("is_custom", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("total_clicks", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="short_urls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "links_shorturl",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="idx_shorturl_owner_created",
                    )
                ],
            },
        ),
    ]
