# Generated by Django 5.1.15 on 2026-09-22 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Click",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("short_code", models.CharField(max_length=32)),
                ("clicked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("referrer", models.CharField(blank=True, max_length=2048, null=True)),
                ("country_code", models.CharField(blank=True, max_length=2, null=True)),
                ("device_type", models.CharField(blank=True, max_length=16, null=True)),
                ("browser", models.CharField(blank=True, max_length=32, null=True)),
                ("os", models.CharField(blank=True, max_length=32, null=True)),
                ("is_bot", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "analytics_click",
                "indexes": [
                    models.Index(
                        fields=["short_code", "-clicked_at"],
                        name="idx_click_code_clicked",
                    ),
                    models.Index(fields=["-clicked_at"], name="idx_click_clicked_at"),
                ],
            },
        ),
    ]
